use usbd_human_interface_device::page::{Keyboard, Consumer};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct KeyboardWrapper (Keyboard);

impl std::fmt::Display for KeyboardWrapper {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self.0 {
            Keyboard::NoEventIndicated => write!(f, "None"),
            Keyboard::ErrorRollOver => write!(f, "Error Roll Over"),
            Keyboard::POSTFail => write!(f, "POST Fail"),
            Keyboard::ErrorUndefine => write!(f, "Error Undefine"),
            Keyboard::A => write!(f, "A"),
            Keyboard::B => write!(f, "B"),
            Keyboard::C => write!(f, "C"),
            Keyboard::D => write!(f, "D"),
            Keyboard::E => write!(f, "E"),
            Keyboard::F => write!(f, "F"),
            Keyboard::G => write!(f, "G"),
            Keyboard::H => write!(f, "H"),
            Keyboard::I => write!(f, "I"),
            Keyboard::J => write!(f, "J"),
            Keyboard::K => write!(f, "K"),
            Keyboard::L => write!(f, "L"),
            Keyboard::M => write!(f, "M"),
            Keyboard::N => write!(f, "N"),
            Keyboard::O => write!(f, "O"),
            Keyboard::P => write!(f, "P"),
            Keyboard::Q => write!(f, "Q"),
            Keyboard::R => write!(f, "R"),
            Keyboard::S => write!(f, "S"),
            Keyboard::T => write!(f, "T"),
            Keyboard::U => write!(f, "U"),
            Keyboard::V => write!(f, "V"),
            Keyboard::W => write!(f, "W"),
            Keyboard::X => write!(f, "X"),
            Keyboard::Y => write!(f, "Y"),
            Keyboard::Z => write!(f, "Z"),
            Keyboard::Keyboard1 => write!(f, "Keyboard 1"),
            Keyboard::Keyboard2 => write!(f, "Keyboard 2"),
            Keyboard::Keyboard3 => write!(f, "Keyboard 3"),
            Keyboard::Keyboard4 => write!(f, "Keyboard 4"),
            Keyboard::Keyboard5 => write!(f, "Keyboard 5"),
            Keyboard::Keyboard6 => write!(f, "Keyboard 6"),
            Keyboard::Keyboard7 => write!(f, "Keyboard 7"),
            Keyboard::Keyboard8 => write!(f, "Keyboard 8"),
            Keyboard::Keyboard9 => write!(f, "Keyboard 9"),
            Keyboard::Keyboard0 => write!(f, "Keyboard 0"),
            Keyboard::ReturnEnter => write!(f, "Return"),
            Keyboard::Escape => write!(f, "Escape"),
            Keyboard::DeleteBackspace => write!(f, "Backspace"),
            Keyboard::Tab => write!(f, "Tab"),
            Keyboard::Space => write!(f, "Space"),
            Keyboard::Minus => write!(f, "Minus"),
            Keyboard::Equal => write!(f, "Equal"),
            Keyboard::LeftBrace => write!(f, "Left Brace"),
            Keyboard::RightBrace => write!(f, "Right Brace"),
            Keyboard::Backslash => write!(f, "Backslash"),
            Keyboard::NonUSHash => write!(f, "Non U SHash"),
            Keyboard::Semicolon => write!(f, "Semicolon"),
            Keyboard::Apostrophe => write!(f, "Apostrophe"),
            Keyboard::Grave => write!(f, "Grave"),
            Keyboard::Comma => write!(f, "Comma"),
            Keyboard::Dot => write!(f, "Dot"),
            Keyboard::ForwardSlash => write!(f, "Forward Slash"),
            Keyboard::CapsLock => write!(f, "Caps Lock"),
            Keyboard::F1 => write!(f, "F1"),
            Keyboard::F2 => write!(f, "F2"),
            Keyboard::F3 => write!(f, "F3"),
            Keyboard::F4 => write!(f, "F4"),
            Keyboard::F5 => write!(f, "F5"),
            Keyboard::F6 => write!(f, "F6"),
            Keyboard::F7 => write!(f, "F7"),
            Keyboard::F8 => write!(f, "F8"),
            Keyboard::F9 => write!(f, "F9"),
            Keyboard::F10 => write!(f, "F10"),
            Keyboard::F11 => write!(f, "F11"),
            Keyboard::F12 => write!(f, "F12"),
            Keyboard::PrintScreen => write!(f, "Print Screen"),
            Keyboard::ScrollLock => write!(f, "Scroll Lock"),
            Keyboard::Pause => write!(f, "Pause"),
            Keyboard::Insert => write!(f, "Insert"),
            Keyboard::Home => write!(f, "Home"),
            Keyboard::PageUp => write!(f, "Page Up"),
            Keyboard::DeleteForward => write!(f, "Delete"),
            Keyboard::End => write!(f, "End"),
            Keyboard::PageDown => write!(f, "Page Down"),
            Keyboard::RightArrow => write!(f, "Right Arrow"),
            Keyboard::LeftArrow => write!(f, "Left Arrow"),
            Keyboard::DownArrow => write!(f, "Down Arrow"),
            Keyboard::UpArrow => write!(f, "Up Arrow"),
            Keyboard::KeypadNumLockAndClear => write!(f, "Keypad Num Lock And Clear"),
            Keyboard::KeypadDivide => write!(f, "Keypad Divide"),
            Keyboard::KeypadMultiply => write!(f, "Keypad Multiply"),
            Keyboard::KeypadSubtract => write!(f, "Keypad Subtract"),
            Keyboard::KeypadAdd => write!(f, "Keypad Add"),
            Keyboard::KeypadEnter => write!(f, "Keypad Enter"),
            Keyboard::Keypad1 => write!(f, "Keypad 1"),
            Keyboard::Keypad2 => write!(f, "Keypad 2"),
            Keyboard::Keypad3 => write!(f, "Keypad 3"),
            Keyboard::Keypad4 => write!(f, "Keypad 4"),
            Keyboard::Keypad5 => write!(f, "Keypad 5"),
            Keyboard::Keypad6 => write!(f, "Keypad 6"),
            Keyboard::Keypad7 => write!(f, "Keypad 7"),
            Keyboard::Keypad8 => write!(f, "Keypad 8"),
            Keyboard::Keypad9 => write!(f, "Keypad 9"),
            Keyboard::Keypad0 => write!(f, "Keypad 0"),
            Keyboard::KeypadDot => write!(f, "Keypad Dot"),
            Keyboard::NonUSBackslash => write!(f, "Non US Backslash"),
            Keyboard::Application => write!(f, "Application"),
            Keyboard::Power => write!(f, "Power"),
            Keyboard::KeypadEqual => write!(f, "Keypad Equal"),
            Keyboard::F13 => write!(f, "F13"),
            Keyboard::F14 => write!(f, "F14"),
            Keyboard::F15 => write!(f, "F15"),
            Keyboard::F16 => write!(f, "F16"),
            Keyboard::F17 => write!(f, "F17"),
            Keyboard::F18 => write!(f, "F18"),
            Keyboard::F19 => write!(f, "F19"),
            Keyboard::F20 => write!(f, "F20"),
            Keyboard::F21 => write!(f, "F21"),
            Keyboard::F22 => write!(f, "F22"),
            Keyboard::F23 => write!(f, "F23"),
            Keyboard::F24 => write!(f, "F24"),
            Keyboard::Execute => write!(f, "Execute"),
            Keyboard::Help => write!(f, "Help"),
            Keyboard::Menu => write!(f, "Menu"),
            Keyboard::Select => write!(f, "Select"),
            Keyboard::Stop => write!(f, "Stop"),
            Keyboard::Again => write!(f, "Again"),
            Keyboard::Undo => write!(f, "Undo"),
            Keyboard::Cut => write!(f, "Cut"),
            Keyboard::Copy => write!(f, "Copy"),
            Keyboard::Paste => write!(f, "Paste"),
            Keyboard::Find => write!(f, "Find"),
            Keyboard::Mute => write!(f, "Mute"),
            Keyboard::VolumeUp => write!(f, "Volume Up"),
            Keyboard::VolumeDown => write!(f, "Volume Down"),
            Keyboard::LockingCapsLock => write!(f, "Locking Caps Lock"),
            Keyboard::LockingNumLock => write!(f, "Locking Num Lock"),
            Keyboard::LockingScrollLock => write!(f, "Locking Scroll Lock"),
            Keyboard::KeypadComma => write!(f, "Keypad Comma"),
            Keyboard::KeypadEqualSign => write!(f, "Keypad Equal Sign"),
            Keyboard::Kanji1 => write!(f, "Kanji 1"),
            Keyboard::Kanji2 => write!(f, "Kanji 2"),
            Keyboard::Kanji3 => write!(f, "Kanji 3"),
            Keyboard::Kanji4 => write!(f, "Kanji 4"),
            Keyboard::Kanji5 => write!(f, "Kanji 5"),
            Keyboard::Kanji6 => write!(f, "Kanji 6"),
            Keyboard::Kanji7 => write!(f, "Kanji 7"),
            Keyboard::Kanji8 => write!(f, "Kanji 8"),
            Keyboard::Kanji9 => write!(f, "Kanji 9"),
            Keyboard::LANG1 => write!(f, "LANG 1"),
            Keyboard::LANG2 => write!(f, "LANG 2"),
            Keyboard::LANG3 => write!(f, "LANG 3"),
            Keyboard::LANG4 => write!(f, "LANG 4"),
            Keyboard::LANG5 => write!(f, "LANG 5"),
            Keyboard::LANG6 => write!(f, "LANG 6"),
            Keyboard::LANG7 => write!(f, "LANG 7"),
            Keyboard::LANG8 => write!(f, "LANG 8"),
            Keyboard::LANG9 => write!(f, "LANG 9"),
            Keyboard::AlternateErase => write!(f, "Alternate Erase"),
            Keyboard::SysReqAttention => write!(f, "Sys Req Attention"),
            Keyboard::Cancel => write!(f, "Cancel"),
            Keyboard::Clear => write!(f, "Clear"),
            Keyboard::Prior => write!(f, "Prior"),
            Keyboard::Return => write!(f, "Return"),
            Keyboard::Separator => write!(f, "Separator"),
            Keyboard::Out => write!(f, "Out"),
            Keyboard::Oper => write!(f, "Oper"),
            Keyboard::ClearAgain => write!(f, "Clear Again"),
            Keyboard::CrSelProps => write!(f, "Cr Sel Props"),
            Keyboard::ExSel => write!(f, "Ex Sel"),
            Keyboard::LeftControl => write!(f, "Left Control"),
            Keyboard::LeftShift => write!(f, "Left Shift"),
            Keyboard::LeftAlt => write!(f, "Left Alt"),
            Keyboard::LeftGUI => write!(f, "Left GUI"),
            Keyboard::RightControl => write!(f, "Right Control"),
            Keyboard::RightShift => write!(f, "Right Shift"),
            Keyboard::RightAlt => write!(f, "Right Alt"),
            Keyboard::RightGUI => write!(f, "Right GUI"),
        }
    }
}

impl From<Keyboard> for KeyboardWrapper {
    fn from(key: Keyboard) -> KeyboardWrapper {
        KeyboardWrapper(key)
    }
}

impl From<KeyboardWrapper> for Keyboard {
    fn from(wrapper: KeyboardWrapper) -> Keyboard {
        wrapper.0
    }
}

impl KeyboardWrapper {
    pub const KEYS: [KeyboardWrapper; 110] = [
        KeyboardWrapper(Keyboard::NoEventIndicated),
        KeyboardWrapper(Keyboard::A),
        KeyboardWrapper(Keyboard::B),
        KeyboardWrapper(Keyboard::C),
        KeyboardWrapper(Keyboard::D),
        KeyboardWrapper(Keyboard::E),
        KeyboardWrapper(Keyboard::F),
        KeyboardWrapper(Keyboard::G),
        KeyboardWrapper(Keyboard::H),
        KeyboardWrapper(Keyboard::I),
        KeyboardWrapper(Keyboard::J),
        KeyboardWrapper(Keyboard::K),
        KeyboardWrapper(Keyboard::L),
        KeyboardWrapper(Keyboard::M),
        KeyboardWrapper(Keyboard::N),
        KeyboardWrapper(Keyboard::O),
        KeyboardWrapper(Keyboard::P),
        KeyboardWrapper(Keyboard::Q),
        KeyboardWrapper(Keyboard::R),
        KeyboardWrapper(Keyboard::S),
        KeyboardWrapper(Keyboard::T),
        KeyboardWrapper(Keyboard::U),
        KeyboardWrapper(Keyboard::V),
        KeyboardWrapper(Keyboard::W),
        KeyboardWrapper(Keyboard::X),
        KeyboardWrapper(Keyboard::Y),
        KeyboardWrapper(Keyboard::Z),
        KeyboardWrapper(Keyboard::ReturnEnter),
        KeyboardWrapper(Keyboard::Escape),
        KeyboardWrapper(Keyboard::DeleteBackspace),
        KeyboardWrapper(Keyboard::Tab),
        KeyboardWrapper(Keyboard::Space),
        KeyboardWrapper(Keyboard::Minus),
        KeyboardWrapper(Keyboard::Equal),
        KeyboardWrapper(Keyboard::LeftBrace),
        KeyboardWrapper(Keyboard::RightBrace),
        KeyboardWrapper(Keyboard::Backslash),
        KeyboardWrapper(Keyboard::Semicolon),
        KeyboardWrapper(Keyboard::Apostrophe),
        KeyboardWrapper(Keyboard::Grave),
        KeyboardWrapper(Keyboard::Comma),
        KeyboardWrapper(Keyboard::Dot),
        KeyboardWrapper(Keyboard::ForwardSlash),
        KeyboardWrapper(Keyboard::CapsLock),
        KeyboardWrapper(Keyboard::F1),
        KeyboardWrapper(Keyboard::F2),
        KeyboardWrapper(Keyboard::F3),
        KeyboardWrapper(Keyboard::F4),
        KeyboardWrapper(Keyboard::F5),
        KeyboardWrapper(Keyboard::F6),
        KeyboardWrapper(Keyboard::F7),
        KeyboardWrapper(Keyboard::F8),
        KeyboardWrapper(Keyboard::F9),
        KeyboardWrapper(Keyboard::F10),
        KeyboardWrapper(Keyboard::F11),
        KeyboardWrapper(Keyboard::F12),
        KeyboardWrapper(Keyboard::PrintScreen),
        KeyboardWrapper(Keyboard::ScrollLock),
        KeyboardWrapper(Keyboard::Pause),
        KeyboardWrapper(Keyboard::Insert),
        KeyboardWrapper(Keyboard::Home),
        KeyboardWrapper(Keyboard::PageUp),
        KeyboardWrapper(Keyboard::DeleteForward),
        KeyboardWrapper(Keyboard::End),
        KeyboardWrapper(Keyboard::PageDown),
        KeyboardWrapper(Keyboard::RightArrow),
        KeyboardWrapper(Keyboard::LeftArrow),
        KeyboardWrapper(Keyboard::DownArrow),
        KeyboardWrapper(Keyboard::UpArrow),
        KeyboardWrapper(Keyboard::KeypadNumLockAndClear),
        KeyboardWrapper(Keyboard::KeypadDivide),
        KeyboardWrapper(Keyboard::KeypadMultiply),
        KeyboardWrapper(Keyboard::KeypadSubtract),
        KeyboardWrapper(Keyboard::KeypadAdd),
        KeyboardWrapper(Keyboard::KeypadEnter),
        KeyboardWrapper(Keyboard::Keypad1),
        KeyboardWrapper(Keyboard::Keypad2),
        KeyboardWrapper(Keyboard::Keypad3),
        KeyboardWrapper(Keyboard::Keypad4),
        KeyboardWrapper(Keyboard::Keypad5),
        KeyboardWrapper(Keyboard::Keypad6),
        KeyboardWrapper(Keyboard::Keypad7),
        KeyboardWrapper(Keyboard::Keypad8),
        KeyboardWrapper(Keyboard::Keypad9),
        KeyboardWrapper(Keyboard::Keypad0),
        KeyboardWrapper(Keyboard::KeypadDot),
        KeyboardWrapper(Keyboard::KeypadEqual),
        KeyboardWrapper(Keyboard::F13),
        KeyboardWrapper(Keyboard::F14),
        KeyboardWrapper(Keyboard::F15),
        KeyboardWrapper(Keyboard::F16),
        KeyboardWrapper(Keyboard::F17),
        KeyboardWrapper(Keyboard::F18),
        KeyboardWrapper(Keyboard::F19),
        KeyboardWrapper(Keyboard::F20),
        KeyboardWrapper(Keyboard::F21),
        KeyboardWrapper(Keyboard::F22),
        KeyboardWrapper(Keyboard::F23),
        KeyboardWrapper(Keyboard::F24),
        // KeyboardWrapper(Keyboard::Execute),
        // KeyboardWrapper(Keyboard::Help),
        // KeyboardWrapper(Keyboard::Menu),
        // KeyboardWrapper(Keyboard::Select),
        // KeyboardWrapper(Keyboard::Stop),
        // KeyboardWrapper(Keyboard::Again),
        // KeyboardWrapper(Keyboard::Undo),
        // KeyboardWrapper(Keyboard::Cut),
        // KeyboardWrapper(Keyboard::Copy),
        // KeyboardWrapper(Keyboard::Paste),
        // KeyboardWrapper(Keyboard::Find),
        // KeyboardWrapper(Keyboard::Mute),
        KeyboardWrapper(Keyboard::VolumeUp),
        KeyboardWrapper(Keyboard::VolumeDown),
        // KeyboardWrapper(Keyboard::LockingCapsLock),
        // KeyboardWrapper(Keyboard::LockingNumLock),
        // KeyboardWrapper(Keyboard::LockingScrollLock),
        KeyboardWrapper(Keyboard::KeypadComma),
        // KeyboardWrapper(Keyboard::KeypadEqualSign),
        // KeyboardWrapper(Keyboard::Kanji1),
        // KeyboardWrapper(Keyboard::Kanji2),
        // KeyboardWrapper(Keyboard::Kanji3),
        // KeyboardWrapper(Keyboard::Kanji4),
        // KeyboardWrapper(Keyboard::Kanji5),
        // KeyboardWrapper(Keyboard::Kanji6),
        // KeyboardWrapper(Keyboard::Kanji7),
        // KeyboardWrapper(Keyboard::Kanji8),
        // KeyboardWrapper(Keyboard::Kanji9),
        // KeyboardWrapper(Keyboard::LANG1),
        // KeyboardWrapper(Keyboard::LANG2),
        // KeyboardWrapper(Keyboard::LANG3),
        // KeyboardWrapper(Keyboard::LANG4),
        // KeyboardWrapper(Keyboard::LANG5),
        // KeyboardWrapper(Keyboard::LANG6),
        // KeyboardWrapper(Keyboard::LANG7),
        // KeyboardWrapper(Keyboard::LANG8),
        // KeyboardWrapper(Keyboard::LANG9),
        // KeyboardWrapper(Keyboard::AlternateErase),
        // KeyboardWrapper(Keyboard::SysReqAttention),
        // KeyboardWrapper(Keyboard::Cancel),
        // KeyboardWrapper(Keyboard::Clear),
        // KeyboardWrapper(Keyboard::Prior),
        // KeyboardWrapper(Keyboard::Return),
        // KeyboardWrapper(Keyboard::Separator),
        // KeyboardWrapper(Keyboard::Out),
        // KeyboardWrapper(Keyboard::Oper),
        // KeyboardWrapper(Keyboard::ClearAgain),
        // KeyboardWrapper(Keyboard::CrSelProps),
        // KeyboardWrapper(Keyboard::ExSel),
        KeyboardWrapper(Keyboard::LeftControl),
        KeyboardWrapper(Keyboard::LeftShift),
        KeyboardWrapper(Keyboard::LeftAlt),
        KeyboardWrapper(Keyboard::LeftGUI),
        KeyboardWrapper(Keyboard::RightControl),
        KeyboardWrapper(Keyboard::RightShift),
        KeyboardWrapper(Keyboard::RightAlt),
        KeyboardWrapper(Keyboard::RightGUI),
    ];
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConsumerWrapper(Consumer);

impl std::fmt::Display for ConsumerWrapper {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self.0 {
            Consumer::Unassigned => write!(f, "Unassigned"),
            Consumer::ConsumerControl => write!(f, "ConsumerControl"),
            Consumer::NumericKeyPad => write!(f, "NumericKeyPad"),
            Consumer::ProgrammableButtons => write!(f, "ProgrammableButtons"),
            Consumer::Microphone => write!(f, "Microphone"),
            Consumer::Headphone => write!(f, "Headphone"),
            Consumer::GraphicEqualizer => write!(f, "GraphicEqualizer"),
            Consumer::Plus10 => write!(f, "Plus10"),
            Consumer::Plus100 => write!(f, "Plus100"),
            Consumer::AmPm => write!(f, "AmPm"),
            Consumer::Power => write!(f, "Power"),
            Consumer::Reset => write!(f, "Reset"),
            Consumer::Sleep => write!(f, "Sleep"),
            Consumer::SleepAfter => write!(f, "SleepAfter"),
            Consumer::SleepMode => write!(f, "SleepMode"),
            Consumer::Illumination => write!(f, "Illumination"),
            Consumer::FunctionButtons => write!(f, "FunctionButtons"),
            Consumer::Menu => write!(f, "Menu"),
            Consumer::MenuPick => write!(f, "MenuPick"),
            Consumer::MenuUp => write!(f, "MenuUp"),
            Consumer::MenuDown => write!(f, "MenuDown"),
            Consumer::MenuLeft => write!(f, "MenuLeft"),
            Consumer::MenuRight => write!(f, "MenuRight"),
            Consumer::MenuEscape => write!(f, "MenuEscape"),
            Consumer::MenuValueIncrease => write!(f, "MenuValueIncrease"),
            Consumer::MenuValueDecrease => write!(f, "MenuValueDecrease"),
            Consumer::DataOnScreen => write!(f, "DataOnScreen"),
            Consumer::ClosedCaption => write!(f, "ClosedCaption"),
            Consumer::ClosedCaptionSelect => write!(f, "ClosedCaptionSelect"),
            Consumer::VcrTv => write!(f, "VcrTv"),
            Consumer::BroadcastMode => write!(f, "BroadcastMode"),
            Consumer::Snapshot => write!(f, "Snapshot"),
            Consumer::Still => write!(f, "Still"),
            Consumer::Selection => write!(f, "Selection"),
            Consumer::AssignSelection => write!(f, "AssignSelection"),
            Consumer::ModeStep => write!(f, "ModeStep"),
            Consumer::RecallLast => write!(f, "RecallLast"),
            Consumer::EnterChannel => write!(f, "EnterChannel"),
            Consumer::OrderMovie => write!(f, "OrderMovie"),
            Consumer::Channel => write!(f, "Channel"),
            Consumer::MediaSelection => write!(f, "MediaSelection"),
            Consumer::MediaSelectComputer => write!(f, "MediaSelectComputer"),
            Consumer::MediaSelectTV => write!(f, "MediaSelectTV"),
            Consumer::MediaSelectWWW => write!(f, "MediaSelectWWW"),
            Consumer::MediaSelectDVD => write!(f, "MediaSelectDVD"),
            Consumer::MediaSelectTelephone => write!(f, "MediaSelectTelephone"),
            Consumer::MediaSelectProgramGuide => write!(f, "MediaSelectProgramGuide"),
            Consumer::MediaSelectVideoPhone => write!(f, "MediaSelectVideoPhone"),
            Consumer::MediaSelectGames => write!(f, "MediaSelectGames"),
            Consumer::MediaSelectMessages => write!(f, "MediaSelectMessages"),
            Consumer::MediaSelectCD => write!(f, "MediaSelectCD"),
            Consumer::MediaSelectVCR => write!(f, "MediaSelectVCR"),
            Consumer::MediaSelectTuner => write!(f, "MediaSelectTuner"),
            Consumer::Quit => write!(f, "Quit"),
            Consumer::Help => write!(f, "Help"),
            Consumer::MediaSelectTape => write!(f, "MediaSelectTape"),
            Consumer::MediaSelectCable => write!(f, "MediaSelectCable"),
            Consumer::MediaSelectSatellite => write!(f, "MediaSelectSatellite"),
            Consumer::MediaSelectSecurity => write!(f, "MediaSelectSecurity"),
            Consumer::MediaSelectHome => write!(f, "MediaSelectHome"),
            Consumer::MediaSelectCall => write!(f, "MediaSelectCall"),
            Consumer::ChannelIncrement => write!(f, "ChannelIncrement"),
            Consumer::ChannelDecrement => write!(f, "ChannelDecrement"),
            Consumer::MediaSelectSAP => write!(f, "MediaSelectSAP"),
            Consumer::VCRPlus => write!(f, "VCRPlus"),
            Consumer::Once => write!(f, "Once"),
            Consumer::Daily => write!(f, "Daily"),
            Consumer::Weekly => write!(f, "Weekly"),
            Consumer::Monthly => write!(f, "Monthly"),
            Consumer::Play => write!(f, "Play"),
            Consumer::Pause => write!(f, "Pause"),
            Consumer::Record => write!(f, "Record"),
            Consumer::FastForward => write!(f, "Fast Forward"),
            Consumer::Rewind => write!(f, "Rewind"),
            Consumer::ScanNextTrack => write!(f, "ScanNextTrack"),
            Consumer::ScanPreviousTrack => write!(f, "ScanPreviousTrack"),
            Consumer::Stop => write!(f, "Stop"),
            Consumer::Eject => write!(f, "Eject"),
            Consumer::RandomPlay => write!(f, "RandomPlay"),
            Consumer::SelectDisc => write!(f, "SelectDisc"),
            Consumer::EnterDisc => write!(f, "EnterDisc"),
            Consumer::Repeat => write!(f, "Repeat"),
            Consumer::Tracking => write!(f, "Tracking"),
            Consumer::TrackNormal => write!(f, "TrackNormal"),
            Consumer::SlowTracking => write!(f, "SlowTracking"),
            Consumer::FrameForward => write!(f, "FrameForward"),
            Consumer::FrameBack => write!(f, "FrameBack"),
            Consumer::Mark => write!(f, "Mark"),
            Consumer::ClearMark => write!(f, "ClearMark"),
            Consumer::RepeatFromMark => write!(f, "RepeatFromMark"),
            Consumer::ReturnToMark => write!(f, "ReturnToMark"),
            Consumer::SearchMarkForward => write!(f, "SearchMarkForward"),
            Consumer::SearchMarkBackwards => write!(f, "SearchMarkBackwards"),
            Consumer::CounterReset => write!(f, "CounterReset"),
            Consumer::ShowCounter => write!(f, "ShowCounter"),
            Consumer::TrackingIncrement => write!(f, "TrackingIncrement"),
            Consumer::TrackingDecrement => write!(f, "TrackingDecrement"),
            Consumer::StopEject => write!(f, "StopEject"),
            Consumer::PlayPause => write!(f, "Play / Pause"),
            Consumer::PlaySkip => write!(f, "PlaySkip"),
            Consumer::Volume => write!(f, "Volume"),
            Consumer::Balance => write!(f, "Balance"),
            Consumer::Mute => write!(f, "Mute"),
            Consumer::Bass => write!(f, "Bass"),
            Consumer::Treble => write!(f, "Treble"),
            Consumer::BassBoost => write!(f, "BassBoost"),
            Consumer::SurroundMode => write!(f, "SurroundMode"),
            Consumer::Loudness => write!(f, "Loudness"),
            Consumer::MPX => write!(f, "MPX"),
            Consumer::VolumeIncrement => write!(f, "Volume Increment"),
            Consumer::VolumeDecrement => write!(f, "Volume Decrement"),
            Consumer::SpeedSelect => write!(f, "SpeedSelect"),
            Consumer::PlaybackSpeed => write!(f, "PlaybackSpeed"),
            Consumer::StandardPlay => write!(f, "StandardPlay"),
            Consumer::LongPlay => write!(f, "LongPlay"),
            Consumer::ExtendedPlay => write!(f, "ExtendedPlay"),
            Consumer::Slow => write!(f, "Slow"),
            Consumer::FanEnable => write!(f, "FanEnable"),
            Consumer::FanSpeed => write!(f, "FanSpeed"),
            Consumer::LightEnable => write!(f, "LightEnable"),
            Consumer::LightIlluminationLevel => write!(f, "LightIlluminationLevel"),
            Consumer::ClimateControlEnable => write!(f, "ClimateControlEnable"),
            Consumer::RoomTemperature => write!(f, "RoomTemperature"),
            Consumer::SecurityEnable => write!(f, "SecurityEnable"),
            Consumer::FireAlarm => write!(f, "FireAlarm"),
            Consumer::PoliceAlarm => write!(f, "PoliceAlarm"),
            Consumer::Proximity => write!(f, "Proximity"),
            Consumer::Motion => write!(f, "Motion"),
            Consumer::DuressAlarm => write!(f, "DuressAlarm"),
            Consumer::HoldupAlarm => write!(f, "HoldupAlarm"),
            Consumer::MedicalAlarm => write!(f, "MedicalAlarm"),
            Consumer::BalanceRight => write!(f, "BalanceRight"),
            Consumer::BalanceLeft => write!(f, "BalanceLeft"),
            Consumer::BassIncrement => write!(f, "BassIncrement"),
            Consumer::BassDecrement => write!(f, "BassDecrement"),
            Consumer::TrebleIncrement => write!(f, "TrebleIncrement"),
            Consumer::TrebleDecrement => write!(f, "TrebleDecrement"),
            Consumer::SpeakerSystem => write!(f, "SpeakerSystem"),
            Consumer::ChannelLeft => write!(f, "ChannelLeft"),
            Consumer::ChannelRight => write!(f, "ChannelRight"),
            Consumer::ChannelCenter => write!(f, "ChannelCenter"),
            Consumer::ChannelFront => write!(f, "ChannelFront"),
            Consumer::ChannelCenterFront => write!(f, "ChannelCenterFront"),
            Consumer::ChannelSide => write!(f, "ChannelSide"),
            Consumer::ChannelSurround => write!(f, "ChannelSurround"),
            Consumer::ChannelLowFrequencyEnhancement => write!(f, "ChannelLowFrequencyEnhancement"),
            Consumer::ChannelTop => write!(f, "ChannelTop"),
            Consumer::ChannelUnknown => write!(f, "ChannelUnknown"),
            Consumer::SubChannel => write!(f, "SubChannel"),
            Consumer::SubChannelIncrement => write!(f, "SubChannelIncrement"),
            Consumer::SubChannelDecrement => write!(f, "SubChannelDecrement"),
            Consumer::AlternateAudioIncrement => write!(f, "AlternateAudioIncrement"),
            Consumer::AlternateAudioDecrement => write!(f, "AlternateAudioDecrement"),
            Consumer::ApplicationLaunchButtons => write!(f, "ApplicationLaunchButtons"),
            Consumer::ALLaunchButtonConfigurationTool => write!(f, "ALLaunchButtonConfigurationTool"),
            Consumer::ALProgrammableButtonConfiguration => write!(f, "ALProgrammableButtonConfiguration"),
            Consumer::ALConsumerControlConfiguration => write!(f, "ALConsumerControlConfiguration"),
            Consumer::ALWordProcessor => write!(f, "ALWordProcessor"),
            Consumer::ALTextEditor => write!(f, "ALTextEditor"),
            Consumer::ALSpreadsheet => write!(f, "ALSpreadsheet"),
            Consumer::ALGraphicsEditor => write!(f, "ALGraphicsEditor"),
            Consumer::ALPresentationApp => write!(f, "ALPresentationApp"),
            Consumer::ALDatabaseApp => write!(f, "ALDatabaseApp"),
            Consumer::ALEmailReader => write!(f, "ALEmailReader"),
            Consumer::ALNewsreader => write!(f, "ALNewsreader"),
            Consumer::ALVoicemail => write!(f, "ALVoicemail"),
            Consumer::ALContactsAddressBook => write!(f, "ALContactsAddressBook"),
            Consumer::ALCalendarSchedule => write!(f, "ALCalendarSchedule"),
            Consumer::ALTaskProjectManager => write!(f, "ALTaskProjectManager"),
            Consumer::ALLogJournalTimecard => write!(f, "ALLogJournalTimecard"),
            Consumer::ALCheckbookFinance => write!(f, "ALCheckbookFinance"),
            Consumer::ALCalculator => write!(f, "ALCalculator"),
            Consumer::ALAvCapturePlayback => write!(f, "ALAvCapturePlayback"),
            Consumer::ALLocalMachineBrowser => write!(f, "ALLocalMachineBrowser"),
            Consumer::ALLanWanBrowser => write!(f, "ALLanWanBrowser"),
            Consumer::ALInternetBrowser => write!(f, "ALInternetBrowser"),
            Consumer::ALRemoteNetworkingISPConnect => write!(f, "ALRemoteNetworkingISPConnect"),
            Consumer::ALNetworkConference => write!(f, "ALNetworkConference"),
            Consumer::ALNetworkChat => write!(f, "ALNetworkChat"),
            Consumer::ALTelephonyDialer => write!(f, "ALTelephonyDialer"),
            Consumer::ALLogon => write!(f, "ALLogon"),
            Consumer::ALLogoff => write!(f, "ALLogoff"),
            Consumer::ALLogonLogoff => write!(f, "ALLogonLogoff"),
            Consumer::ALTerminalLockScreensaver => write!(f, "ALTerminalLockScreensaver"),
            Consumer::ALControlPanel => write!(f, "ALControlPanel"),
            Consumer::ALCommandLineProcessorRun => write!(f, "ALCommandLineProcessorRun"),
            Consumer::ALProcessTaskManager => write!(f, "ALProcessTaskManager"),
            Consumer::ALSelectTaskApplication => write!(f, "ALSelectTaskApplication"),
            Consumer::ALNextTaskApplication => write!(f, "ALNextTaskApplication"),
            Consumer::ALPreviousTaskApplication => write!(f, "ALPreviousTaskApplication"),
            Consumer::ALPreemptiveHaltTaskApplication => write!(f, "ALPreemptiveHaltTaskApplication"),
            Consumer::ALIntegratedHelpCenter => write!(f, "ALIntegratedHelpCenter"),
            Consumer::ALDocuments => write!(f, "ALDocuments"),
            Consumer::ALThesaurus => write!(f, "ALThesaurus"),
            Consumer::ALDictionary => write!(f, "ALDictionary"),
            Consumer::ALDesktop => write!(f, "ALDesktop"),
            Consumer::ALSpellCheck => write!(f, "ALSpellCheck"),
            Consumer::ALGrammarCheck => write!(f, "ALGrammarCheck"),
            Consumer::ALWirelessStatus => write!(f, "ALWirelessStatus"),
            Consumer::ALKeyboardLayout => write!(f, "ALKeyboardLayout"),
            Consumer::ALVirusProtection => write!(f, "ALVirusProtection"),
            Consumer::ALEncryption => write!(f, "ALEncryption"),
            Consumer::ALScreenSaver => write!(f, "ALScreenSaver"),
            Consumer::ALAlarms => write!(f, "ALAlarms"),
            Consumer::ALClock => write!(f, "ALClock"),
            Consumer::ALFileBrowser => write!(f, "ALFileBrowser"),
            Consumer::ALPowerStatus => write!(f, "ALPowerStatus"),
            Consumer::ALImageBrowser => write!(f, "ALImageBrowser"),
            Consumer::ALAudioBrowser => write!(f, "ALAudioBrowser"),
            Consumer::ALMovieBrowser => write!(f, "ALMovieBrowser"),
            Consumer::ALDigitalRightsManager => write!(f, "ALDigitalRightsManager"),
            Consumer::ALDigitalWallet => write!(f, "ALDigitalWallet"),
            Consumer::ALInstantMessaging => write!(f, "ALInstantMessaging"),
            Consumer::ALOemFeaturesTipsTutorialBrowser => write!(f, "ALOemFeaturesTipsTutorialBrowser"),
            Consumer::ALOemHelp => write!(f, "ALOemHelp"),
            Consumer::ALOnlineCommunity => write!(f, "ALOnlineCommunity"),
            Consumer::ALEntertainmentContentBrowser => write!(f, "ALEntertainmentContentBrowser"),
            Consumer::ALOnlineShoppingBrowser => write!(f, "ALOnlineShoppingBrowser"),
            Consumer::ALSmartCardInformationHelp => write!(f, "ALSmartCardInformationHelp"),
            Consumer::ALMarketMonitorFinanceBrowser => write!(f, "ALMarketMonitorFinanceBrowser"),
            Consumer::ALCustomizedCorporateNewsBrowser => write!(f, "ALCustomizedCorporateNewsBrowser"),
            Consumer::ALOnlineActivityBrowser => write!(f, "ALOnlineActivityBrowser"),
            Consumer::ALResearchSearchBrowser => write!(f, "ALResearchSearchBrowser"),
            Consumer::ALAudioPlayer => write!(f, "ALAudioPlayer"),
            Consumer::GenericGUIApplicationControls => write!(f, "GenericGUIApplicationControls"),
            Consumer::ACNew => write!(f, "ACNew"),
            Consumer::ACOpen => write!(f, "ACOpen"),
            Consumer::ACClose => write!(f, "ACClose"),
            Consumer::ACExit => write!(f, "ACExit"),
            Consumer::ACMaximize => write!(f, "ACMaximize"),
            Consumer::ACMinimize => write!(f, "ACMinimize"),
            Consumer::ACSave => write!(f, "ACSave"),
            Consumer::ACPrint => write!(f, "ACPrint"),
            Consumer::ACProperties => write!(f, "ACProperties"),
            Consumer::ACUndo => write!(f, "ACUndo"),
            Consumer::ACCopy => write!(f, "ACCopy"),
            Consumer::ACCut => write!(f, "ACCut"),
            Consumer::ACPaste => write!(f, "ACPaste"),
            Consumer::ACSelectAll => write!(f, "ACSelectAll"),
            Consumer::ACFind => write!(f, "ACFind"),
            Consumer::ACFindAndReplace => write!(f, "ACFindAndReplace"),
            Consumer::ACSearch => write!(f, "ACSearch"),
            Consumer::ACGoTo => write!(f, "ACGoTo"),
            Consumer::ACHome => write!(f, "ACHome"),
            Consumer::ACBack => write!(f, "ACBack"),
            Consumer::ACForward => write!(f, "ACForward"),
            Consumer::ACStop => write!(f, "ACStop"),
            Consumer::ACRefresh => write!(f, "ACRefresh"),
            Consumer::ACPreviousLink => write!(f, "ACPreviousLink"),
            Consumer::ACNextLink => write!(f, "ACNextLink"),
            Consumer::ACBookmarks => write!(f, "ACBookmarks"),
            Consumer::ACHistory => write!(f, "ACHistory"),
            Consumer::ACSubscriptions => write!(f, "ACSubscriptions"),
            Consumer::ACZoomIn => write!(f, "ACZoomIn"),
            Consumer::ACZoomOut => write!(f, "ACZoomOut"),
            Consumer::ACZoom => write!(f, "ACZoom"),
            Consumer::ACFullScreenView => write!(f, "ACFullScreenView"),
            Consumer::ACNormalView => write!(f, "ACNormalView"),
            Consumer::ACViewToggle => write!(f, "ACViewToggle"),
            Consumer::ACScrollUp => write!(f, "ACScrollUp"),
            Consumer::ACScrollDown => write!(f, "ACScrollDown"),
            Consumer::ACScroll => write!(f, "ACScroll"),
            Consumer::ACPanLeft => write!(f, "ACPanLeft"),
            Consumer::ACPanRight => write!(f, "ACPanRight"),
            Consumer::ACPan => write!(f, "ACPan"),
            Consumer::ACNewWindow => write!(f, "ACNewWindow"),
            Consumer::ACTileHorizontally => write!(f, "ACTileHorizontally"),
            Consumer::ACTileVertically => write!(f, "ACTileVertically"),
            Consumer::ACFormat => write!(f, "ACFormat"),
            Consumer::ACEdit => write!(f, "ACEdit"),
            Consumer::ACBold => write!(f, "ACBold"),
            Consumer::ACItalics => write!(f, "ACItalics"),
            Consumer::ACUnderline => write!(f, "ACUnderline"),
            Consumer::ACStrikethrough => write!(f, "ACStrikethrough"),
            Consumer::ACSubscript => write!(f, "ACSubscript"),
            Consumer::ACSuperscript => write!(f, "ACSuperscript"),
            Consumer::ACAllCaps => write!(f, "ACAllCaps"),
            Consumer::ACRotate => write!(f, "ACRotate"),
            Consumer::ACResize => write!(f, "ACResize"),
            Consumer::ACFlipHorizontal => write!(f, "ACFlipHorizontal"),
            Consumer::ACFlipVertical => write!(f, "ACFlipVertical"),
            Consumer::ACMirrorHorizontal => write!(f, "ACMirrorHorizontal"),
            Consumer::ACMirrorVertical => write!(f, "ACMirrorVertical"),
            Consumer::ACFontSelect => write!(f, "ACFontSelect"),
            Consumer::ACFontColor => write!(f, "ACFontColor"),
            Consumer::ACFontSize => write!(f, "ACFontSize"),
            Consumer::ACJustifyLeft => write!(f, "ACJustifyLeft"),
            Consumer::ACJustifyCenterH => write!(f, "ACJustifyCenterH"),
            Consumer::ACJustifyRight => write!(f, "ACJustifyRight"),
            Consumer::ACJustifyBlockH => write!(f, "ACJustifyBlockH"),
            Consumer::ACJustifyTop => write!(f, "ACJustifyTop"),
            Consumer::ACJustifyCenterV => write!(f, "ACJustifyCenterV"),
            Consumer::ACJustifyBottom => write!(f, "ACJustifyBottom"),
            Consumer::ACJustifyBlockV => write!(f, "ACJustifyBlockV"),
            Consumer::ACIndentDecrease => write!(f, "ACIndentDecrease"),
            Consumer::ACIndentIncrease => write!(f, "ACIndentIncrease"),
            Consumer::ACNumberedList => write!(f, "ACNumberedList"),
            Consumer::ACRestartNumbering => write!(f, "ACRestartNumbering"),
            Consumer::ACBulletedList => write!(f, "ACBulletedList"),
            Consumer::ACPromote => write!(f, "ACPromote"),
            Consumer::ACDemote => write!(f, "ACDemote"),
            Consumer::ACYes => write!(f, "ACYes"),
            Consumer::ACNo => write!(f, "ACNo"),
            Consumer::ACCancel => write!(f, "ACCancel"),
            Consumer::ACCatalog => write!(f, "ACCatalog"),
            Consumer::ACBuyCheckout => write!(f, "ACBuyCheckout"),
            Consumer::ACAddToCart => write!(f, "ACAddToCart"),
            Consumer::ACExpand => write!(f, "ACExpand"),
            Consumer::ACExpandAll => write!(f, "ACExpandAll"),
            Consumer::ACCollapse => write!(f, "ACCollapse"),
            Consumer::ACCollapseAll => write!(f, "ACCollapseAll"),
            Consumer::ACPrintPreview => write!(f, "ACPrintPreview"),
            Consumer::ACPasteSpecial => write!(f, "ACPasteSpecial"),
            Consumer::ACInsertMode => write!(f, "ACInsertMode"),
            Consumer::ACDelete => write!(f, "ACDelete"),
            Consumer::ACLock => write!(f, "ACLock"),
            Consumer::ACUnlock => write!(f, "ACUnlock"),
            Consumer::ACProtect => write!(f, "ACProtect"),
            Consumer::ACUnprotect => write!(f, "ACUnprotect"),
            Consumer::ACAttachComment => write!(f, "ACAttachComment"),
            Consumer::ACDeleteComment => write!(f, "ACDeleteComment"),
            Consumer::ACViewComment => write!(f, "ACViewComment"),
            Consumer::ACSelectWord => write!(f, "ACSelectWord"),
            Consumer::ACSelectSentence => write!(f, "ACSelectSentence"),
            Consumer::ACSelectParagraph => write!(f, "ACSelectParagraph"),
            Consumer::ACSelectColumn => write!(f, "ACSelectColumn"),
            Consumer::ACSelectRow => write!(f, "ACSelectRow"),
            Consumer::ACSelectTable => write!(f, "ACSelectTable"),
            Consumer::ACSelectObject => write!(f, "ACSelectObject"),
            Consumer::ACRedoRepeat => write!(f, "ACRedoRepeat"),
            Consumer::ACSort => write!(f, "ACSort"),
            Consumer::ACSortAscending => write!(f, "ACSortAscending"),
            Consumer::ACSortDescending => write!(f, "ACSortDescending"),
            Consumer::ACFilter => write!(f, "ACFilter"),
            Consumer::ACSetClock => write!(f, "ACSetClock"),
            Consumer::ACViewClock => write!(f, "ACViewClock"),
            Consumer::ACSelectTimeZone => write!(f, "ACSelectTimeZone"),
            Consumer::ACEditTimeZones => write!(f, "ACEditTimeZones"),
            Consumer::ACSetAlarm => write!(f, "ACSetAlarm"),
            Consumer::ACClearAlarm => write!(f, "ACClearAlarm"),
            Consumer::ACSnoozeAlarm => write!(f, "ACSnoozeAlarm"),
            Consumer::ACResetAlarm => write!(f, "ACResetAlarm"),
            Consumer::ACSynchronize => write!(f, "ACSynchronize"),
            Consumer::ACSendReceive => write!(f, "ACSendReceive"),
            Consumer::ACSendTo => write!(f, "ACSendTo"),
            Consumer::ACReply => write!(f, "ACReply"),
            Consumer::ACReplyAll => write!(f, "ACReplyAll"),
            Consumer::ACForwardMsg => write!(f, "ACForwardMsg"),
            Consumer::ACSend => write!(f, "ACSend"),
            Consumer::ACAttachFile => write!(f, "ACAttachFile"),
            Consumer::ACUpload => write!(f, "ACUpload"),
            Consumer::ACDownloadSaveTargetAs => write!(f, "ACDownloadSaveTargetAs"),
            Consumer::ACSetBorders => write!(f, "ACSetBorders"),
            Consumer::ACInsertRow => write!(f, "ACInsertRow"),
            Consumer::ACInsertColumn => write!(f, "ACInsertColumn"),
            Consumer::ACInsertFile => write!(f, "ACInsertFile"),
            Consumer::ACInsertPicture => write!(f, "ACInsertPicture"),
            Consumer::ACInsertObject => write!(f, "ACInsertObject"),
            Consumer::ACInsertSymbol => write!(f, "ACInsertSymbol"),
            Consumer::ACSaveAndClose => write!(f, "ACSaveAndClose"),
            Consumer::ACRename => write!(f, "ACRename"),
            Consumer::ACMerge => write!(f, "ACMerge"),
            Consumer::ACSplit => write!(f, "ACSplit"),
            Consumer::ACDistributeHorizontally => write!(f, "ACDistributeHorizontally"),
            Consumer::ACDistributeVertically => write!(f, "ACDistributeVertically"),
        }
    }
}

impl ConsumerWrapper {
    pub const KEYS: [ConsumerWrapper; 7] = [
        ConsumerWrapper(Consumer::VolumeDecrement),
        ConsumerWrapper(Consumer::VolumeIncrement),
        ConsumerWrapper(Consumer::Play),
        ConsumerWrapper(Consumer::Pause),
        ConsumerWrapper(Consumer::PlayPause),
        ConsumerWrapper(Consumer::FastForward),
        ConsumerWrapper(Consumer::Rewind),
    ];
}

impl From<Consumer> for ConsumerWrapper {
    fn from(consumer: Consumer) -> ConsumerWrapper {
        ConsumerWrapper(consumer)
    }
}

impl From<ConsumerWrapper> for Consumer {
    fn from(wrapper: ConsumerWrapper) -> Consumer {
        wrapper.0
    }
}